from Exercise_3_Try_Except import try_except

try_except(8, 7)